version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt compile
      - sbt assembly
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir target/lib
      - cp target/scala-2.11/lambda-demo-assembly-1.0.jar target/lib
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket testbucket-77 --output-template-file target/NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - target/lib/lambda-demo-assembly-1.0.jar
    - target/NewSamTemplate.yaml